#!/bin/bash

content=$(</dev/stdin)

if [ -f ./repo-format.json ];
then
	echo "$content" | ./node_modules/repo-format/node_modules/.bin/esformatter --config ./repo-format.json;
else
	echo "$content"
fi
