#!/bin/bash

content=$(</dev/stdin)

if [ -f ./local-format.json ];
then
	echo "$content" | ./node_modules/repo-format/node_modules/.bin/esformatter --config ./local-format.json;
elif [ -f ~/.local-format.json ];
then
	echo "$content" | ./node_modules/repo-format/node_modules/.bin/esformatter --config ~/.local-format.json;
else
	echo "$content"
fi
